name: gaza_exchange_app
description: "تطبيق تبادل السلع والعقارات لغزة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management & Navigation
  get: ^4.6.6
  
  # HTTP Client
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  
  # Image Handling
  image_picker: ^1.0.4
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utils
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts - تم إزالتها مؤقتاً حتى إضافة ملفات الخط
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700

  # إضافة مجلد assets إذا كان موجود
